import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import Navigation from '@/components/Navigation';
import Header from '@/components/Header';
import "./globals.css";

import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "dark min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <main className="flex min-h-screen flex-col items-center justify-between p-10 sm:p-24">
          <Header />
          {children}
          <Navigation />
        </main>
      </body>
    </html>
  );
}
